function sym_poly_fit = contraction_fit_poly(p)
%CONTRACTION_FIT_POLY
%    SYM_POLY_FIT = CONTRACTION_FIT_POLY(P)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    31-Dec-2021 13:37:37

t2 = conj(p);
et1 = t2.*(-8.616576226209145e-4)-t2.^2.*1.351653816985491e-4+t2.^3.*4.567416494750149e-6-t2.^4.*5.593052717700519e-8;
et2 = t2.^5.*2.401903882589948e-10+4.422327617975142e-1;
sym_poly_fit = et1+et2;
