function sym_fit = contraction_fit(p)
%CONTRACTION_FIT
%    SYM_FIT = CONTRACTION_FIT(P)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    06-Jul-2022 19:12:00

sym_fit = exp(p.*(-2.749409489935759e-2)).*1.197431377157744e-1+3.283609484951821e-1;
