function sym_poly_fit = contraction_fit_poly(p)
%CONTRACTION_FIT_POLY
%    SYM_POLY_FIT = CONTRACTION_FIT_POLY(P)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    29-Oct-2022 14:03:09

t2 = conj(p);
et1 = t2.*(-8.616576226209122e-4)-t2.^2.*1.351653816985496e-4+t2.^3.*4.56741649475017e-6-t2.^4.*5.593052717700555e-8;
et2 = t2.^5.*2.401903882589969e-10+4.422327617975142e-1;
sym_poly_fit = et1+et2;
