function sym_fit = contraction_fit(p)
%CONTRACTION_FIT
%    SYM_FIT = CONTRACTION_FIT(P)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Nov-2021 20:30:19

sym_fit = exp(p.*(-2.748196542051478e-2)).*1.197539732503461e-1+3.283431769071775e-1;
