body_defaults:
  position_noise: 0.01
  rotation_noise: 0.003

default_body: snake
bodies:
  - lab:
      is_static: true
      default_tag_size: 0.031
      type: simple
      pose:
        position:
          x: 0
          y: 0
          z: 0
        rotation:
          x: 0
          y: 0
          z: 0
        position_noise:
          x: 0.0001
          y: 0.0001
          z: 0.0001
        rotation_noise:
          x: 1.0e-05
          y: 1.0e-05
          z: 1.0e-05

      tags:
        # Default tag for lab
        - id: 0
          pose:
            position:
              x: 0
              y: 0
              z: 0
            rotation:
              x: 0
              y: 0
              z: 0
            position_noise:
              x: 0.0001
              y: 0.0001
              z: 0.0001
            rotation_noise:
              x: 1.0e-05
              y: 1.0e-05
              z: 1.0e-05
        - id: 1
          pose:
            position:
              x: 0.035
              y: 0
              z: 0
            rotation:
              x: 0
              y: 0
              z: 0
            position_noise:
              x: 0.0001
              y: 0.0001
              z: 0.0001
            rotation_noise:
              x: 1.0e-05
              y: 1.0e-05
              z: 1.0e-05
        - id: 2
          pose:
            position:
              x: 0.07
              y: 0
              z: 0
            rotation:
              x: 0
              y: 0
              z: 0
            position_noise:
              x: 0.0001
              y: 0.0001
              z: 0.0001
            rotation_noise:
              x: 1.0e-05
              y: 1.0e-05
              z: 1.0e-05
        - id: 3
          pose:
            position:
              x: 0.105
              y: 0
              z: 0
            rotation:
              x: 0
              y: 0
              z: 0
            position_noise:
              x: 0.0001
              y: 0.0001
              z: 0.0001
            rotation_noise:
              x: 1.0e-05
              y: 1.0e-05
              z: 1.0e-05
        - id: 4
          pose:
            position:
              x: 0.140
              y: 0
              z: 0
            rotation:
              x: 0
              y: 0
              z: 0
            position_noise:
              x: 0.0001
              y: 0.0001
              z: 0.0001
            rotation_noise:
              x: 1.0e-05
              y: 1.0e-05
              z: 1.0e-05
        - id: 5
          pose:
            position:
              x: 0.175
              y: 0
              z: 0
            rotation:
              x: 0
              y: 0
              z: 0
            position_noise:
              x: 0.0001
              y: 0.0001
              z: 0.0001
            rotation_noise:
              x: 1.0e-05
              y: 1.0e-05
              z: 1.0e-05

  - snake:
      is_static: true
      default_tag_size: 0.031
      pose:
        position:
          x: 0.21
          y: 0
          z: 0.0127
        rotation:
          x: 0
          y: 0
          z: 0
        position_noise:
          x: 0.02
          y: 0.02
          z: 0.02
        rotation_noise:
          x: 0.1
          y: 0.1
          z: 0.1
      type: simple

      tags:
        # Default tag for snakes
        - id: 6
          size: 0.031
          pose:
            position:
              x: 0
              y: 0
              z: 0
            rotation:
              x: 0
              y: 0
              z: 0
            position_noise:
              x: 0.001
              y: 0.001
              z: 0.001
            rotation_noise:
              x: 0.005
              y: 0.005
              z: 0.005
        - id: 7
        - id: 8
        - id: 9

  - rig:
      is_static: false
      type: simple
      odom_frame_id: body_rig