body_defaults:
  position_noise: 0.01
  rotation_noise: 0.003

default_body: lab
bodies:
  - lab:
      is_static: true
      default_tag_size: 0.031
      type: simple
      pose:
        position:
          x: 0
          y: 0
          z: 0
        rotation:
          x: 0
          y: 0
          z: 0
        position_noise:
          x: 0.0001
          y: 0.0001
          z: 0.0001
        rotation_noise:
          x: 1.0e-05
          y: 1.0e-05
          z: 1.0e-05

      tags:
        # Default tag for lab
        - id: 0
          pose:
            position:
              x: 0
              y: 0.1524 # 6 inches in meter
              z: 0
            rotation:
              x: 0
              y: 0
              z: 0
            position_noise:
              x: 0.0001
              y: 0.0001
              z: 0.0001
            rotation_noise:
              x: 1.0e-05
              y: 1.0e-05
              z: 1.0e-05

  - rig:
      is_static: false
      type: simple
      odom_frame_id: body_rig