body_defaults:
  position_noise: 0.01
  rotation_noise: 0.003

default_body: lab
bodies:
  - lab:
      is_static: true
      default_tag_size: 0.031
      type: simple
      pose:
        position:
          x: 0
          y: 0
          z: 0
        rotation:
          x: 0
          y: 0
          z: 0
        position_noise:
          x: 0.0001
          y: 0.0001
          z: 0.0001
        rotation_noise:
          x: 1.0e-05
          y: 1.0e-05
          z: 1.0e-05

      tags:
        # Default tag for snakes
        - id: 5
          size: 0.031
          pose:
            position:
              x: 0
              y: 0
              z: 0
            rotation:
              x: 0
              y: 0
              z: 0
            position_noise:
              x: 0.001
              y: 0.001
              z: 0.001
            rotation_noise:
              x: 0.005
              y: 0.005
              z: 0.005

  - rig:
      is_static: false
      type: simple
      odom_frame_id: body_rig
