cam0:
  camera_model: pinhole
  intrinsics: [956.24189, 957.68864, 597.31480, 336.69868]
  distortion_model: plumb_bob
  distortion_coeffs: [-0.01245, -0.10039, -0.00349, -0.02133, 0.00000]
  resolution: [1280, 720]
  rostopic: /annotated_images/image_raw
  tagtopic: /detector/tags
  rig_body: rig
